version: 0.2

phases:
  install:
    commands:
      - echo "Installing Corretto 25..."
      - yum install -y java-25-amazon-corretto-devel
      - java -version

  pre_build:
    commands:
      - echo "Pre-build started on $(date)"

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean package -DskipTests
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Post-build started on $(date)"
      - echo "web: java -jar ordering-app-0.0.1-SNAPSHOT.jar" > Procfile
      - echo "Post-build completed on $(date)"

artifacts:
  files:
    - target/ordering-app-0.0.1-SNAPSHOT.jar
    - Procfile
  discard-paths: yes

cache:
  paths:
    - /root/.m2/**/*