spring.application.name=ordering-app

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/MenuOptions}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.show-sql=true